-- TASK: Create a customer_preferences table with the following columns:
-- - customer_id (INT, Foreign Key to users.user_id)
-- - privacy_level (VARCHAR(20) with CHECK constraint for 'public', 'private', 'restricted')
-- - email_notifications (BOOLEAN DEFAULT true)
-- - data_retention_days (INT DEFAULT 365)
-- - created_at (TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
-- - updated_at (TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
--
-- Include proper indexes, foreign key constraints, and CHECK constraints
-- Add an index on customer_id for performance

-- YOUR CODE HERE